dbconf:
  ssl: True or False
  host: host adress
  port: port
  user: username
  password: password
  db: database name
  tinput: table from third party name
  tuni: table to unisender api name
  tsms: table to SMS relay name
uniconf:
  key: unisender api key
  pluslist: list to paste entrys from api
goipconf:
  host: host adress
  port: port
  user: username of admin
  password: password of admin
  simcount: number of active SIM cards in relay
  messages:
    - first message
    - second message